from django.urls import path
from . import views

app_name = "store_app"

urlpatterns = [
    path(
        '', 
        views.HomePageView.as_view(), 
        name='pub_articulos'
    ),
    path(
        'inform-contact', 
        views.ContactPageView.as_view(), 
        name='inform_contact'
    ),
    path(
        'about-exo', 
        views.aboutExonica.as_view(), 
        name='about_exo'
    ),
    path(
        'articulo-pub/<slug>/', 
        views.ArticulosDetailView.as_view(), 
        name='articulo_pub'
    ),
    path(
        'articulo-categoria/', 
        views.ArticulosPorCategorias.as_view(), 
        name='articulo_categoria'
    ),
    path(
        'mensaje-contacto/', 
        views.MensajeCreateView.as_view(), 
        name='mensaje_contacto'
    ),
    path(
        'car-shop/', 
        views.CarPageView.as_view(), 
        name='car_shop'
    ),
    path(
        'add-car-shop/<pk>/', 
        views.AddCarView.as_view(), 
        name='add_car_shop'
    ),
    path(
        'api/num-car/', 
        views.CarNumApiView.as_view(),
    ),
    path(
        'eliminar-producto/<pk>/', 
        views.CarDeleteView.as_view(), 
        name='eliminar_producto'
    ),
    path(
        'eliminar-todo', 
        views.CarDeleteViewAll.as_view(), 
        name='eliminar_todo'
    ),
    path(
        'payment-paypal/', 
        views.PaymentView.as_view(), 
        name='payment_paypal'
    ),
    path(
        'payment-trans/', 
        views.PaymentViewTrans.as_view(), 
        name='payment_trans'
    ),
    path(
        'confirm-order/', 
        views.confirmOrderView.as_view(), 
        name='confirm_order'
    ),
    path(
        'gracias-por-comprar/', 
        views.GraciasPorComprarView.as_view(), 
        name='gracias_comprar'
    ),
    path(
        'historial-compras/', 
        views.historialComprasView.as_view(), 
        name='historial_compras'
    ),
    path(
        'rest-car/<pk>/', 
        views.CarShopUpdateViewRest.as_view(), 
        name='rest_car'
    ),
    path(
        'sum-car/<pk>/', 
        views.CarShopUpdateViewMas.as_view(), 
        name='sum_car'
    ),
]