# Generated by Django 3.2.6 on 2022-01-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_exonica', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncios',
            name='mensaje',
            field=models.TextField(verbose_name='Mensaje'),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción'),
        ),
    ]
