# Generated by Django 3.2.6 on 2022-01-04 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_exonica', '0003_auto_20220104_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='user',
            field=models.CharField(max_length=30, verbose_name='usuario'),
        ),
    ]
