# Generated by Django 3.2.6 on 2022-01-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_exonica', '0004_alter_articulos_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos',
            name='instalacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='articulos',
            name='precio_inst',
            field=models.DecimalField(decimal_places=0, default=False, max_digits=7, verbose_name='Precio de la instalación'),
        ),
    ]
