# Generated by Django 3.2.6 on 2022-01-14 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_exonica', '0005_auto_20220114_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulos',
            name='instalacion',
        ),
    ]
