# Generated by Django 3.2.6 on 2022-01-15 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_exonica', '0006_remove_articulos_instalacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='precio_inst',
            field=models.DecimalField(decimal_places=0, max_digits=7, verbose_name='Precio de la instalación'),
        ),
    ]
