# Generated by Django 3.2.6 on 2022-01-15 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_exonica', '0007_alter_articulos_precio_inst'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos',
            name='precio_inst_fuera',
            field=models.DecimalField(decimal_places=0, default=False, max_digits=7, verbose_name='Precio de la instalación fuera de sonora'),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='precio_inst',
            field=models.DecimalField(decimal_places=0, max_digits=7, verbose_name='Precio de la instalación en sonora'),
        ),
    ]
