# Generated by Django 3.2.6 on 2022-01-15 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_exonica', '0008_auto_20220114_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='precio_inst_fuera',
            field=models.DecimalField(decimal_places=0, max_digits=7, verbose_name='Precio de la instalación fuera de sonora'),
        ),
    ]
