from django.urls import path

from . import views


app_name = "app_admin"

urlpatterns = [
    path(
        'categoria-crear/', 
        views.CategoriaArticulosCreateView.as_view(), 
        name='categoria_crear'
    ),
    path(
        'articulos-crear/', 
        views.ArticulosCreateView.as_view(), 
        name='articulos_crear'
    ),
    path(
        'articulos-lista/', 
        views.listarArticulosListView.as_view(), 
        name='articulos_listar'
    ),
    path(
        'categoria-lista/', 
        views.listarCategoriasListView.as_view(), 
        name='categoria_listar'
    ),
    path(
        'payments-lista/', 
        views.listarPayments.as_view(), 
        name='payments_listar'
    ),
    path(
        'categoria-eliminar/<pk>/', 
        views.CategoriaDeleteView.as_view(), 
        name='categoria_eliminar'
    ),
    path(
        'categoria-editar/<pk>/', 
        views.CategoriaUpdateView.as_view(), 
        name='categoria_editar'
    ),
    path(
        'articulo-eliminar/<pk>/', 
        views.ArticulosDeleteView.as_view(), 
        name='articulo_eliminar'
    ),
    path(
        'articulo-editar/<pk>/', 
        views.ArticulosUpdateView.as_view(), 
        name='articulo_editar'
    ),
    path(
        'anuncios-crear/', 
        views.AnunciosCreateView.as_view(), 
        name='anuncios'
    ),
    path(
        'anuncios-listar/', 
        views.listarAnunciosListView.as_view(), 
        name='anuncios_listar'
    ),
    path(
        'anuncios-editar/<pk>/', 
        views.AnuncioUpdateView.as_view(), 
        name='anuncios_editar'
    ),
      path(
        'anuncios-eliminar/<pk>/', 
        views.AnunciosDeleteView.as_view(), 
        name='anuncios_eliminar'
    ),
    path(
        'mensajes-lista/', 
        views.listarMensjaesListView.as_view(), 
        name='mensajes_listar'
    ),
    path(
        'mensaje-ver/<pk>/', 
        views.MensajeDetailView.as_view(), 
        name='mensaje_ver'
    ),
    path(
        'procesar-msj/<pk>/', 
        views.procesarMsjView.as_view(), 
        name='procesar_msj'
    ),
    path(
        'mensaje-eliminar/<pk>/', 
        views.MensajeDeleteView.as_view(), 
        name='mensaje_eliminar'
    ),
    path(
        'editar-payment/<pk>/', 
        views.DatosPaymentUpdateView.as_view(), 
        name='editar_payment'
    ),
    path(
        'delete-payment/<pk>/', 
        views.PaymentDeleteView.as_view(), 
        name='delete_payment'
    ),
    path(
        'about-exo/', 
        views.quienSomosView.as_view(), 
        name='about_exo'
    ),
    path(
        'editar-about-exo/<pk>/', 
        views.quienesSomosUpdateView.as_view(), 
        name='editar_about_exo'
    ),
]