# Generated by Django 3.2.6 on 2022-01-10 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220110_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cpostal',
            field=models.CharField(max_length=6, verbose_name='Codigo Postal'),
        ),
    ]
