# Generated by Django 3.2.6 on 2022-01-03 02:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_exonica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('articulos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulos_favoritos', to='admin_exonica.articulos')),
            ],
            options={
                'verbose_name': 'Articulo favorito',
                'verbose_name_plural': 'Articulos favoritos',
            },
        ),
    ]
