# Generated by Django 3.2.6 on 2022-01-03 02:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_exonica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('count', models.PositiveIntegerField(verbose_name='Cantidad')),
            ],
            options={
                'verbose_name': 'Carrito de compras',
                'verbose_name_plural': 'Carrito de compras',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='DatosContacExo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=30, verbose_name='Titulo')),
                ('about_text', models.TextField(verbose_name='Información sobre exonica')),
                ('contac_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email de contacto')),
                ('phone', models.CharField(max_length=15, verbose_name='telefono de contacto')),
            ],
            options={
                'verbose_name': 'Pagina principal',
                'verbose_name_plural': 'Pagina Principal',
            },
        ),
        migrations.CreateModel(
            name='FormContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('full_name', models.CharField(max_length=60, verbose_name='Nombres')),
                ('email', models.EmailField(max_length=254)),
                ('celphone', models.CharField(blank=True, max_length=10, verbose_name='Celular')),
                ('message', models.TextField(max_length=200, verbose_name='Mensaje')),
                ('read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Mensajes',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('payment_method', models.CharField(choices=[('PayPal', 'PayPal'), ('Transferencia', 'Transferencia')], max_length=20)),
                ('amount', models.FloatField()),
                ('succesful', models.BooleanField()),
                ('raw_response', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('EN PROCESO DE ENVIO', 'EN PROCESO DE ENVIO'), ('EN CAMINO', 'EN CAMINO'), ('ENTREGADO', 'ENTREGADO')], default='EN PROCESO DE ENVIO', max_length=20)),
                ('envio', models.FloatField()),
            ],
            options={
                'verbose_name': 'Payment',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('count', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('price_sale', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Venta')),
                ('anulate', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_sale', to='admin_exonica.articulos', verbose_name='producto')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_payment', to='store_exonica.payment')),
            ],
            options={
                'verbose_name': 'Producto Vendido',
                'verbose_name_plural': 'Productos vendidos',
            },
        ),
    ]
