# Generated by Django 3.2.6 on 2022-01-03 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_exonica', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datoscontacexo',
            name='about_text',
        ),
        migrations.AddField(
            model_name='datoscontacexo',
            name='direccion',
            field=models.TextField(null=True, verbose_name='Dirección de exonica'),
        ),
        migrations.AlterField(
            model_name='datoscontacexo',
            name='contac_email',
            field=models.EmailField(max_length=254, verbose_name='email de contacto'),
        ),
    ]
