# Generated by Django 3.2.6 on 2022-01-03 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_exonica', '0003_auto_20220102_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datoscontacexo',
            name='direccion',
            field=models.TextField(verbose_name='Dirección de exonica'),
        ),
    ]
