# Generated by Django 3.2.6 on 2022-01-04 02:49

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store_exonica', '0004_alter_datoscontacexo_direccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutExonica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('qsomos', models.TextField(max_length=500, verbose_name='Quienes somos')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='datoscontacexo',
            name='direccion',
            field=models.CharField(max_length=70, verbose_name='Dirección de exonica'),
        ),
    ]
