# Generated by Django 3.2.6 on 2022-01-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_exonica', '0005_auto_20220103_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='folio',
            field=models.CharField(default=False, max_length=60, verbose_name='Folio de la transación'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('EN PROCESO DE ENVIO', 'VERIFICANDO DATOS'), ('EN PROCESO DE ENVIO', 'EN PROCESO DE ENVIO'), ('EN CAMINO', 'EN CAMINO'), ('ENTREGADO', 'ENTREGADO')], default='EN PROCESO DE ENVIO', max_length=20),
        ),
    ]
