# Generated by Django 3.2.6 on 2022-01-06 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_exonica', '0006_auto_20220106_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='folio',
            field=models.CharField(blank=True, max_length=60, verbose_name='Folio de la transación'),
        ),
    ]
