# Generated by Django 3.2.6 on 2022-01-10 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_exonica', '0007_alter_payment_folio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('VERIFICANDO DATOS', 'VERIFICANDO DATOS'), ('EN PROCESO DE ENVIO', 'EN PROCESO DE ENVIO'), ('EN CAMINO', 'EN CAMINO'), ('ENTREGADO', 'ENTREGADO')], default='EN PROCESO DE ENVIO', max_length=20),
        ),
    ]
