# Generated by Django 3.2.6 on 2022-01-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_exonica', '0009_alter_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('VERIFICANDO DATOS', 'VERIFICANDO DATOS'), ('EN PROCESO DE ENVIO', 'EN PROCESO DE ENVIO'), ('EN CAMINO', 'EN CAMINO'), ('ENTREGADO', 'ENTREGADO')], max_length=20),
        ),
    ]
