# Generated by Django 3.2.6 on 2022-01-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_exonica', '0010_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='folio',
            field=models.CharField(max_length=60, verbose_name='Folio de la transación'),
        ),
    ]
