# Generated by Django 3.2.6 on 2022-01-12 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_exonica', '0011_alter_payment_folio'),
    ]

    operations = [
        migrations.AddField(
            model_name='carshop',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=False, max_digits=10, verbose_name='Precio Venta'),
        ),
    ]
