# Generated by Django 3.2.6 on 2022-01-12 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_exonica', '0012_carshop_subtotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carshop',
            name='subtotal',
        ),
    ]
