# Generated by Django 3.2.6 on 2022-01-14 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_exonica', '0015_alter_carshop_subtotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdetail',
            name='anulate',
        ),
    ]
