# Generated by Django 3.2.6 on 2022-01-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_exonica', '0016_remove_paymentdetail_anulate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='folio',
        ),
        migrations.AddField(
            model_name='payment',
            name='comprobante_pago',
            field=models.ImageField(default=False, upload_to='comprobantes_de_pago', verbose_name='Comprobante de pago'),
        ),
    ]
