# Generated by Django 3.2.6 on 2022-01-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_exonica', '0017_auto_20220114_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='comprobante_pago',
            field=models.ImageField(null=True, upload_to='comprobantes_de_pago', verbose_name='Comprobante de pago'),
        ),
    ]
