# Generated by Django 3.2.6 on 2022-01-14 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_exonica', '0018_alter_payment_comprobante_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='carshop',
            name='instalacion',
            field=models.BooleanField(default=False),
        ),
    ]
