# Generated by Django 3.2.6 on 2022-01-14 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_exonica', '0019_carshop_instalacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carshop',
            name='instalacion',
            field=models.BooleanField(),
        ),
    ]
