# Generated by Django 3.2.6 on 2022-01-14 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_exonica', '0021_auto_20220114_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='costo_instalacion',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Instalación'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='instalacion',
            field=models.BooleanField(),
        ),
    ]
