# Generated by Django 3.2.6 on 2022-01-15 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_exonica', '0022_auto_20220114_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='costo_instalacion',
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='costo_instalacion',
            field=models.DecimalField(decimal_places=2, default=False, max_digits=10, verbose_name='Instalación'),
        ),
    ]
