# Generated by Django 3.2.6 on 2022-02-12 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_exonica', '0025_auto_20220114_1709'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DatosContacExo',
        ),
    ]
